=== code-monki/central-supply-catalog/schemas/product.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://code-monki.github.io/central-supply-catalog/schemas/product.schema.json",
  "title": "Central Supply Catalog Product",
  "type": "object",
  "required": ["sku", "type", "subtype", "tags"],
  "additionalProperties": true,
  "properties": {
    "sku": {
      "type": "string",
      "pattern": "^[0-9]{3}-[0-9]{3}-[0-9]{4,6}$"
    },
    "type": {
      "type": "string",
      "minLength": 1
    },
    "subtype": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "mfr": {
      "type": "string"
    },
    "cost": {
      "type": "number",
      "minimum": 0
    },
    "mass": {
      "type": ["number", "string"]
    },
    "size": {
      "type": ["number", "string"]
    },
    "techLevel": {
      "type": "number",
      "minimum": 0
    },
    "qrebs": {
      "type": "string"
    },
    "damage": {
      "type": "string"
    },
    "image": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "displacement": {
      "type": "number"
    },
    "stats": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "accessories": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[0-9]{3}-[0-9]{3}-[0-9]{4,6}$"
      }
    },
    "variants": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["sku", "label"],
        "additionalProperties": true,
        "properties": {
          "sku": {
            "type": "string",
            "pattern": "^[0-9]{3}-[0-9]{3}-[0-9]{4,6}$"
          },
          "label": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "sources": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["publication", "authors", "publisher"],
        "additionalProperties": true,
        "properties": {
          "publication": {
            "type": "string",
            "minLength": 1
          },
          "url": {
            "type": "string"
          },
          "authors": {
            "type": "array",
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "publisher": {
            "anyOf": [
              {
                "type": "string",
                "minLength": 1
              },
              {
                "type": "object",
                "required": ["name"],
                "additionalProperties": true,
                "properties": {
                  "name": {
                    "type": "string",
                    "minLength": 1
                  },
                  "url": {
                    "type": "string"
                  }
                }
              }
            ]
          }
        }
      }
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "sku": {
            "pattern": "-00000$"
          }
        },
        "required": ["sku"]
      },
      "then": true,
      "else": {
        "required": ["name", "cost", "techLevel", "qrebs", "image", "description", "sources"]
      }
    }
  ]
}

=== code-monki/central-supply-catalog/src/_data/products/dress/130-001-10049.json
{
  "sku": "130-001-10049",
  "type": "protections",
  "subtype": "dress",
  "name": "Boarding Dress, Modified (ModBdD-15)",
  "mfr": "",
  "cost": 192000,
  "mass": 43,
  "techLevel": 15,
  "qrebs": "N/A",
  "image": "",
  "description": "<p><!-- Summary Start -->Boarding dress is tailored for zero-G operations against interplanetary and interstellar vessels.<!-- Summary End --></p>",
  "accessories": [],
  "categories": [
    "protections",
    "dress"
  ],
  "sources": [
    {
      "publication": "Traveller 5.10 Core Rules Book 1 : Characters and Combat",
      "authors": [
        "Miller, Marc"
      ],
      "publisher": {
        "name": "Far Future Enterprises",
        "url": "https://farfuture.net"
      }
    }
  ],
  "tags": [
    "products",
    "protections",
    "dress"
  ]
}

=== code-monki/central-supply-catalog/src/_data/products/armor/130-000-00044.json
{
  "sku": "130-000-00044",
  "type": "protections",
  "subtype": "armor",
  "name": "Combat Armor, Improved Vlight (ImVlCbtA-13)",
  "mfr": "",
  "cost": 176000,
  "mass": 36,
  "techLevel": 13,
  "qrebs": "N/A",
  "image": "",
  "description": "<p><!-- Summary Start -->Combat armor is intended for medium-term operations (days) against an enemy force.<!-- Summary End --></p>",
  "accessories": [],
  "categories": ["protections", "armor"],
  "sources": [
    {
      "publication": "Traveller 5.10 Core Rules Book 1 : Characters and Combat",
      "authors": ["Miller, Marc"],
      "publisher": "Far Future Enterprises"
    }
  ],
  "tags": ["products", "protections", "armor"]
}

=== code-monki/central-supply-catalog/src/_data/products/robots/140-000-00013.json
{
  "sku": "140-000-00013",
  "type": "robotics",
  "subtype": "robots",
  "name": "AN-427 class Security Robot",
  "mfr": "015",
  "cost": 1810523,
  "mass": 1685,
  "techLevel": 12,
  "qrebs": "N/A",
  "image": "",
  "description": "<p><!-- Summary Start -->The AN-427 class Security Robot is a security robot.<!-- Summary End --> The ICAM Technology AN-427 security robot was a widely used security robot throughout the Imperium before the Collapse and has survived in considerable numbers due to its rugged reliability. It was programmed to patrol all areas of a sensitive installation, seek out and kill or incapacitate unauthorized intruders. Although it is not as mobile as grav-powered units, it is less expensive to operate, and replacement parts are easier to fabricate. This is a wheeled robot which experiences difficulty negotiating stairs, ladders, and any uneven ground. This robot is powered by internal batteries which require recharging every four days. It is armed with a Laser rifle and a 10mm CPR gun firing tranq rounds.</p>",
  "categories": [
    "robotics", "robots"
  ],
  "sources": [
    {
      "publication": "Traveller Wiki : AN-427 class Security Robot",
      "authors": [
        "Traveller Wiki Editorial Team",
        "Lord (Marquis) and Master of Sophontology Maksim-Smelchak of the Ministry of Science"
      ],
      "publisher": {
        "name": "Traveller Wiki",
        "url": "https://wiki.travellerrpg.com/AN-427_class_Security_Robot"
      }
    },
    {
      "publication": "Vampire Fleets",
      "authors": [
        "Chadwick, Frank"
      ],
      "publisher": {
        "name": "Game Designers Workshop",
        "url": ""
      }
    }
  ],
  "tags": [
    "products",
    "robotics",
    "robots"
  ]
}

=== code-monki/central-supply-catalog/src/_data/products/cyberware/130-004-00010.json
{
  "sku": "130-004-00010",
  "type": "protections",
  "subtype": "cyberware",
  "name": "Synthetic G-I Tract",
  "mfr": "",
  "cost": 80000,
  "mass": 3.5,
  "size": "5 liters",
  "techLevel": 8,
  "qrebs": "N/A",
  "image": "",
  "description": "<p><!-- Summary Start -->The Synthetic G-I Tract replaces the small intestine, the large intestine and the mesentery with a composite system of filters and biochemical processing chambers that mimic the usual intestinal processes.<!-- Summary End --> Individuals equipped with this system also undergo a rectal replacement that means feces are no longer produced. Instead, a solid, odorless pellet is produced that can be easily and discreetly ejected.</p><p>It may be connected to a Cybernetic Stomach and a Synthetic Liver to completely replace an individual's digestive system. The system may be enhanced with a toxin Filter, ingested material can be filtered to remove toxins that would cause harm if they were passed into the bloodstream, making the individual immune to all ingested poisons.</p><p>The exact size and dimensions of the G-I Tract are tailored to match the physical characteristics of the recipient. It is powered by tiny thermoelectric generators that produce the needed electrical power from body heat and from chemical reactions.The various parts of the G-I Tract, including elements such as the casings, sacs, microelectronics, and connections to the circulatory system are made with biocompatible materials. These may include metal alloys, carbon nanotubes, silicon gels, and layered polymers.</p><p>Similar devices have been in use since the days of the First Imperium. They reached their modern form through Terran medical advances achieved during the Interstellar Wars period.</p>",
  "categories": [
    "protections",
    "cyberware"
  ],
  "sources": [
    {
      "publication": "Traveller Wiki: Synthetic G-I Tract",
      "authors": [
        "Lord (Marquis) and Master Scout Emeritus Adie Alegoric Stewart of the IISS"
      ],
      "publisher": {
        "name": "Traveller Wiki",
        "url": "https://wiki.travellerrpg.com/Synthetic_G-I_Tract"
      }
    },
    {
      "publication": "Cybernetics",
      "authors": [
        "Nash, Pete",
        "Robinson, Nick"
      ],
      "publisher": {
        "name": "Mongoose Publishing",
        "url": "https://www.mongoosepublishing.com/"
      }
    }
  ],
  "tags": [
    "products",
    "protections",
    "cyberware"
  ]
}

=== code-monki/central-supply-catalog/src/_data/products/ammunition/200-010-00141.json
{
  "sku": "200-010-00141",
  "type": "weapons",
  "subtype": "ammunition",
  "name": "6mm Accelerator Rifle Ammunition - 10D damage",
  "mfr": "",
  "cost": 1000,
  "mass": 0.95,
  "techLevel": 8,
  "qrebs": "N/A",
  "image": "",
  "variants": [
    { "sku": "200-010-00132", "label": "1D Damage" },
    { "sku": "200-010-00133", "label": "2D Damage" },
    { "sku": "200-010-00134", "label": "3D Damage" },
    { "sku": "200-010-00135", "label": "4D Damage" },
    { "sku": "200-010-00136", "label": "5D Damage" },
    { "sku": "200-010-00137", "label": "6D Damage" },
    { "sku": "200-010-00138", "label": "7D Damage" },
    { "sku": "200-010-00139", "label": "8D Damage" },
    { "sku": "200-010-00140", "label": "9D Damage" },
    { "sku": "200-010-00141", "label": "10D Damage" }
  ],
  "description": "<p><!-- Summary Start -->Standard 6mm Accelerator Rifle round, 10D damage, 100 round box.<!-- Summary End --></p>",
  "categories": ["weapons", "ammunition"],
  "sources": [
    {
      "publication": "Traveller 5.10 Core Rules Book 3 : Worlds and Adventures",
      "authors": ["Miller, Marc W."],
      "publisher": "Far Future Enterprises"
    },
    {
      "publication": "Central Supply Catalog Website : 6mm Accelerator Rifle Ammunition -  10D Damage",
      "url": "/products/200-010-00141",
      "authors": ["Miller, Marc W.", "Eaglestone, Robert", "McKnight, Charles"],
      "publisher": "Central Supply Catalog Website"
    }
  ],
  "tags": ["products", "weapons", "ammunition"]
}

=== code-monki/central-supply-catalog/src/_data/products/machineguns/200-004-00040.json
{
  "sku": "200-004-00040",
  "type": "weapons",
  "subtype": "machineguns",
  "name": "Anti-Designator Assault Machinegun, Crewed, Basic (BaDAMgC-11)",
  "mfr": "",
  "cost": 9450,
  "mass": 24,
  "size": "",
  "techLevel": 11,
  "qrebs": "R=5",
  "damage": "Bang-1, Blast-3, Bullet-4",
  "image": "",
  "description": "<p><!-- Summary Start -->Basic version of the crewed anti-designator assault machinegun.<!-- Summary End --></p>",
  "stats": [],
  "categories": [
    "weapons",
    "machineguns"
  ],
  "sources": [
    {
      "publication": "Traveller 5.10 Core Rules Book 1 : Characters and Combat",
      "authors": [
        "Miller, Marc"
      ],
      "publisher": {
        "name": "Far Future Enterprises",
        "url": "https://farfuture.net"
      }
    },
    {
      "publication": "Traveller 5.10 Core Rules Book 3 : Worlds and Adventures",
      "authors": [
        "Miller, Marc"
      ],
      "publisher": {
        "name": "Far Future Enterprises",
        "url": "https://farfuture.net"
      }
    }
  ],
  "tags": [
    "products",
    "weapons",
    "machineguns"
  ]
}

=== code-monki/central-supply-catalog/src/_data/products/suits/130-002-10056.json
{
  "sku": "130-002-10056",
  "type": "protections",
  "subtype": "suits",
  "name": "Protected Suit, Titan (TPrS-15)",
  "cost": 30000,
  "mass": 81,
  "techLevel": 15,
  "qrebs": "N/A",
  "image": "",
  "description": "<p><!-- Summary Start -->Protected suits protect the wearer from most environmental threats.<!-- Summary End --></p>",
  "accessories": [],
  "categories": ["protections", "suits"],
  "sources": [
    {
      "publication": "Traveller 5.10 Core Rules Book 1 : Characters and Combat",
      "authors": ["Miller, Marc"],
      "publisher": {
        "name": "Far Future Enterprises",
        "url": "https://www.farfuture.net"
      }
    }
  ],
  "tags": ["products", "protections", "suits"]
}

=== code-monki/central-supply-catalog/src/_data/products/spacecraft/180-002-00002.json
{
  "sku": "180-002-00002",
  "type": "transportation",
  "subtype": "spacecraft",
  "name": "Type A Free Trader",
  "mfr": "",
  "cost": 32100000,
  "displacement": 200,
  "techLevel": 10,
  "qrebs": "N/A",
  "image": "/img/products/180-002-00002.png",
  "description": "<p><!-- Summary Start -->The TL-10 Beowulf-class Free Trader is a short-haul itinerant merchant ship plying the space lanes carrying both cargo and passengers.<!-- Summary End --> The ship is typically capable of Jump-1.</p>",
  "categories": ["transportation", "spacecraft"],
  "sources": [
    {
      "publication": "Traveller 5.10 Core Rules Book 2 : Starships",
      "authors": ["Miller, Marc"],
      "publisher": "Far Future Enterprises"
    }
  ],
  "tags": ["products", "transportation", "spacecraft"]
}
